name: Build & Deploy

on:
  push:
    paths:
      - "data/**"
      - "templates/**"
      - "generate_site.py"
      - "requirements.txt"
      - ".github/workflows/build-and-deploy.yml"
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Generate site
        env:
          BASE_URL: https://Yug2704.github.io/cost-of-living
        run: python generate_site.py
      - uses: actions/upload-pages-artifact@v3
        with: { path: public }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: { pages: write, id-token: write }
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
